Repository redhat-cop/pipeline-library, pull requests merged in 2019-12, with the labels that each got.

#99 Updated release to 1.5.0
  pom.xml
Labels: approved, lgtm

#100 Updated to next snapshot - 1.6.0
  pom.xml
Labels: approved, lgtm

#101 Added 9th param to fix miss-match due to plugin version update
  test/Jenkinsfile-sonarqubeStaticAnalysis
  test/create-sonarqube-installation.groovy
Labels: approved, lgtm

#97 Updated rollout / rollback to allow for different kinds to be supported
  test/Jenkinsfile-rollback
  test/Jenkinsfile-rollback-fail-missingdc
  test/Jenkinsfile-rollout
  test/Jenkinsfile-rollout-deployment
  test/Jenkinsfile-rollout-fail-missingdc
  vars/rollback.groovy
  vars/rollout.groovy
  vars/tagAndDeploy.groovy
Labels: approved, lgtm

#102 Added scale to 0 replicas once test is finished for envs with restrictive quotas
  test/Jenkinsfile-applyTemplate
  test/Jenkinsfile-applyTemplate-viahttp
  test/Jenkinsfile-applyTemplate-withparams
  test/Jenkinsfile-rollback
  test/Jenkinsfile-rollout
  test/Jenkinsfile-tagAndDeploy
  test/Jenkinsfile-verifyDeployment
Labels: approved, lgtm

#94 Added applier to automate testing
  .applier/group_vars/seed-hosts.yml
  .applier/hosts
  .gitignore
  .openshift/templates/build-pipelines.j2
  TESTING.md
  _test/setup.sh
  galaxy-requirements.yml
  meta/main.yml
  requirements.yml
  roles/configure-jenkins/defaults/main.yml
  roles/configure-jenkins/tasks/main.yml
  roles/link-secret/tasks/main.yml
  roles/process-tests/defaults/main.yml
  roles/process-tests/tasks/main.yml
Labels: approved, lgtm

#103 Updated variable used to get describe history
  vars/rollout.groovy
Labels: approved, lgtm

#104 Allow custom namespace in tests
  .applier/group_vars/seed-hosts.yml
  _test/setup.sh
  galaxy-requirements.yml
  roles/process-tests/tasks/main.yml
  test/Jenkinsfile-buildAndTag
  test/Jenkinsfile-crossClusterPromote
  test/Jenkinsfile-imageMirror
  test/Jenkinsfile-rollout-deployment
  test/Jenkinsfile-sonarqubeStaticAnalysis
  test/Jenkinsfile-tagAndDeploy
  test/Jenkinsfile-tagImage
Labels: approved

#105 Updated docs to use latest config and follow same formatting
  vars/applier.txt
  vars/applyTemplate.txt
  vars/binaryBuild.txt
  vars/buildAndTag.txt
  vars/clusterCredentials.txt
  vars/configMap.txt
  vars/crossClusterPromote.txt
  vars/imageMirror.txt
  vars/patchBuildConfigOutputLabels.txt
  vars/rollback.txt
  vars/rollout.txt
  vars/sonarqubeStaticAnalysis.txt
  vars/tagAndDeploy.txt
  vars/tagImage.txt
  vars/verifyDeployment.txt
Labels: approved, lgtm, size/XXL

#106 Added verifyService method
  TESTING.md
  roles/configure-jenkins/tasks/main.yml
  test/Jenkinsfile-verifyService
  test/Jenkinsfile-verifyService-fail-nopods
  vars/verifyService.groovy
  vars/verifyService.txt
Labels: approved, lgtm, size/L

#107 Updated applier test to use testing namespace naming
  .applier/group_vars/seed-hosts.yml
  TESTING.md
  test/Jenkinsfile-applier
  test/Jenkinsfile-buildAndTag
  test/Jenkinsfile-crossClusterPromote
  test/Jenkinsfile-imageMirror
  test/Jenkinsfile-sonarqubeStaticAnalysis
  test/Jenkinsfile-tagImage
Labels: approved, lgtm, size/S
